### ISSUE TITLE
How do you handle Jupyter Notebooks / Markdown / HTML?

### ISSUE THREAD

**Issue by jackeown** [harvardnlp/harvardnlp.github.io#5]
Sorry if this is a bad place for this, but I read your post on Named Tensors and I thought it looked very professional. I'm curious how you integrated a jupyter notebook so well into your website. I saw online that you can convert a jupyter notebook to html via `jupyter nbconvert --to html notebook_name.ipynb`, but your post seemed stylistically better. 

Did you make those alterations manually with css or was there some other software you used? I would like some insight into what you did to make such a beautiful post from a jupyter notebook

Thanks,
Jack McKeown

**Comment by srush** [comment]
Sure, happy to help. I played with this for a bit. 

The command I used was: 
ipython3 nbconvert --template jekyll.tpl --config jekyll.py NamedTensor.ipynb                                                                                                    

I committed the templates in: 
https://github.com/harvardnlp/namedtensor/tree/master/notebooks

And the Jekyll formatting is in: 
https://github.com/harvardnlp/harvardnlp.github.io/blob/master/_config.yml

It's basically the defaults with a bit bootstrap css .

**Comment by jackeown** [comment]
Thank you so much!
